### ISSUE TITLE
What versioins do need to be shared with the author?

### ISSUE THREAD

**Issue by johanneswilm** [OSCOSS/OJSFWplugin#29]
Current state
----

Currently, the author either gets read-without-comments or write access to any new submission revision that is beign created. But does this really make sense? We are talking about these:

Submission: 
  - submission file (read access)

Round 1:
  - reviewer's file (read access)
  - author's file (write access)

Round 2:
  - reviewer's file (read access)
  - author's file (write access)

Issues: Too many files for author. Quickly chaotic.

Proposal 1:
----
Limit author's access to only those versions that include write access:

Submission: 
  - none

Round 1:
  - author's file (write access)

Round 2:
  - author's file (write access)

Issues: When submission has been made, it is unclear to user that the submission has taken place at all.

Proposal 2:
----
Like proposal 1, but with access to the submission file:

Submission: 
  - submission file (read access)

Round 1:
  - author's file (write access)

Round 2:
  - author's file (write access)

Issues: It shows that the submission has been made, but it may still be unclear what files relate to each other in what way.

Proposal 3:
----
Only keep the very latest version in FW, and upload all "older" versions as .fidus or .odt files into OJS.

Issues: .odt file will be an imperfect export .fidus file may be difficult for end user to open.

Proposal 4:
----
Don't show any of the documents or only a limited number on the overview page. Instead create a "Submissions" tab that shows submissions and their current state.

**Comment by afshinsadeghi** [comment]
Authors should always have the write access to the current version, and any time he submits a version the submitted work should not be editable anymore. This is for the sake of comparison.  Reviewers should be able to compare the last submitted versions and the new submitted version, therefore they should not be editable.  

We did not want to upload any document to OJS as we want to keep FW as the place of documents so that individuals can comment over them "in place." 

I understand the name confusion problem, Therefore we tried adding version numbers in the table that lists the documents in FW. I guess, Fakhri did not finish with it, but we have the issue in the github for it in the FW github page. It can get enhanced, by adding the concept of Project.  In addition, we can define a project (folder) per article, and keep all the versions in that directory.
